name: tests

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      run: |
        wget https://dot.net/v1/dotnet-install.sh
        ./dotnet-install.sh -Channel 3.1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  
  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      run: |
        https://dot.net/v1/dotnet-install.ps1 -Channel 3.1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
  build_mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      run: |
        wget https://dot.net/v1/dotnet-install.sh
        ./dotnet-install.sh -Channel 3.1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal     
